### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by heimdall-asguard** [coinbase/dexter#15]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/dexter/compare/a6bc93dae8356d1427e971f915ae5708f48b6058...8de127c499b77909d5837956d16d52ea98e700f5) was merged to master by hkparker.

Comment with appropriate number of :+1: to approve.

**Comment by heimdall-asguard** [comment]
Reviews      | 0/1
------------ | -------------




[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/dexter&ref=2e6e649a596f747c74e5cdd6436423a5f527563f)

**Comment by zblach** [comment]
👍

**Comment by heimdall-asguard** [comment]
Review Error for zblach @ 2018-12-12 21:08:32 UTC
User must have admin permissions to review bad push issue

**Comment by zblach** [comment]
👍

**Comment by heimdall-asguard** [comment]
Review Error for zblach @ 2018-12-12 21:09:02 UTC
User must have admin permissions to review bad push issue

**Comment by brad-larson** [comment]
👍

**Comment by heimdall-asguard** [comment]
Review Error for brad-larson @ 2018-12-12 21:09:59 UTC
User must have write permissions to review

**Comment by sds** [comment]
👍

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1
------------ | -------------
sds | 1

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/dexter&ref=2e6e649a596f747c74e5cdd6436423a5f527563f)
